### PR TITLE
Parser fix synchronisation bugs

### LINKED ISSUE #34: Fix Synchronisation Bugs between Parser and PersonList Class

### PR DESCRIPTION
**Pull request by 1szheng**
Fixes #34

### CODE REVIEW

File: src/main/java/seedu/planitarium/parser/Parser.java [hunk 1]
```diff
@@ -120,7 +121,10 @@ public static void isValidMoney(String amount) throws NumberFormatException {
      */
     public static void isValidUserIndex(String userIndex) throws NumberFormatException, IndexOutOfBoundsException {
         int checkIndex = Integer.parseInt(userIndex);
-        if (checkIndex < MIN_USER_INDEX || checkIndex >= PersonList.getNumberOfMembers()) {
+        if (checkIndex < MIN_USER_INDEX) {
+            throw new IndexOutOfBoundsException();
+        }
+        if (checkIndex >= PersonList.getNumberOfMembers()) {
```
Comment (hlwang56) [inline src/main/java/seedu/planitarium/parser/Parser.java:127]: if you would like to check the index, you may use a seperate boolean function to check it as it is the requirement of coding standard.

Comment (1szheng) [reply src/main/java/seedu/planitarium/parser/Parser.java:127]: Thank you, will implement in future PR, will leave this PR to be focused on the bug fix

**Review by HansHengGit — APPROVED** [review]
