### PR TITLE
Make printing of monetary values 2dp and fix small UG issues

### LINKED ISSUE #194: [PE-D] Documentation can be confusing
The category index is not standardised

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Anvitha-r/ped#8

### LINKED ISSUE #196: [PE-D] contradicting documentation
-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Anvitha-r/ped#9

### LINKED ISSUE #227: [Code review] @teanweijun
1. Restructure code logically and make the happy path prominent

-  refactor below lines such that that guard clause checking isSilent can be executed before the group is created. 

- decompose the so line that getList(group)  and addPerson(name) to the group into two lines. 

Screenshot 2022-04-04 at 11 40 07 PM
 

2.  The system println statement with specific string format can be abstracted out as `printFormattedString()` to ensure SLAP.
Screenshot 2022-04-04 at 11 40 46 PM

### LINKED ISSUE #238: Ensure printing of 2dp Monetary values

### LINKED ISSUE #239: Fix DG formatting error in deletein and deleteout

### PR DESCRIPTION
**Pull request by Teanweijun**
Fixes #194 
Fixes #196 
Fixes #227 
Fixes #238 
Fixes #239

### CODE REVIEW

File: src/main/java/seedu/planitarium/family/Family.java [hunk 1]
```diff
@@ -174,34 +185,33 @@ public void overview() {
...
-            return ("-$" + (-entry));
-        }
-        return ("$" + entry);
+    private void printFormattedOverview(int index, String income, String expenditure, String disposable,
+                                        String generation) {
+        System.out.println(index + ". " + generation + ":" + System.lineSeparator()
+                + Constants.INDENTATION + "Income: " + income + System.lineSeparator()
+                + Constants.INDENTATION + "Expenditure: " + expenditure + System.lineSeparator()
+                + Constants.INDENTATION + "Disposable: " + disposable + System.lineSeparator());
     }
```
Comment (tjiarong) [inline src/main/java/seedu/planitarium/family/Family.java:215]: Same idea as above, can consider using String.format with constants.

File: src/main/java/seedu/planitarium/family/Family.java [hunk 2]
```diff
@@ -94,6 +95,16 @@ public void addPerson(int group, String name, Boolean isSilent) {
...
+
+    /**
+     * Prints the name of the person added, and to which array list.
+     *
+     * @param name The name of the person added
+     * @param generation The group the person is added to
+     */
+    private void printPersonAdded(String name, String generation) {
         System.out.println(name + " has been successfully added to " + generation);
     }
```
Comment (tjiarong) [inline src/main/java/seedu/planitarium/family/Family.java:109]: Possibly consider using String.format instead and shifts the value into constants.

E.g. String.format(CONSTANT, args)

File: src/test/java/seedu/planitarium/global/UiTest.java [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+public class UiTest {
+    private static final Double VALID_AMOUNT = 1000.0;
+    private static final Double NEGATIVE_AMOUNT = -1000.0;
+    private static final Double THREE_DP_AMOUNT = 123.456;
+
+    @Test
+    public void formatValue_negativeValue_minusInFrontOfDollar() {
+        Family family = new Family();
+        Double value = NEGATIVE_AMOUNT;
+        assertEquals("-$1000.00", UI.formatValue(value));
```
Comment (tjiarong) [inline src/test/java/seedu/planitarium/global/UiTest.java:17]: Consider shifting money string into constants

File: src/test/java/seedu/planitarium/global/UiTest.java [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+    }
+
+    @Test
+    public void formatValue_notNegativeValue_noMinusInFrontOfDollar() {
+        Family family = new Family();
+        Double value = VALID_AMOUNT;
+        assertEquals("$1000.00", UI.formatValue(value));
```
Comment (tjiarong) [inline src/test/java/seedu/planitarium/global/UiTest.java:24]: Consider shifting money string into constants

File: src/test/java/seedu/planitarium/global/UiTest.java [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+    }
+
+    @Test void formatValue_moreThan2DecimalPointValue_print2DP() {
+        Family family = new Family();
+        Double value = THREE_DP_AMOUNT;
+        assertEquals("$123.46", UI.formatValue(value));
```
Comment (tjiarong) [inline src/test/java/seedu/planitarium/global/UiTest.java:30]: Consider shifting money string into constants

**Review by tjiarong — APPROVED** [review]
